### ISSUE TITLE
Tooltip stuck in top right corner of screen.

### ISSUE THREAD

**Issue by Razoroth** [LiangYuxuan/InvasionTimer#1]
No matter where I put this broker on TitanPanel, the tooltip always shows in the upper left most area of my screen. No options to reposition or move it. All other plugin tooltips in TitanPanel show at their respective buttons except for this one.

**Comment by LiangYuxuan** [comment]
Sorry for late reply. It is fixed in v8.3.1, by letting tooltip anchored to cursor. Try out latest release :)
